// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Laeeqdev/urlShortner/API/Repository"
	"github.com/Laeeqdev/urlShortner/API/RestHandler"
	"github.com/Laeeqdev/urlShortner/API/Router"
	"github.com/Laeeqdev/urlShortner/API/Services"
)

// Injectors from app.go:

func InitializeApp() *router.RouterImpl {
	longUrlToShortUrlMap := repository.ProvideLongUrlToShortUrlMap()
	shortUrlToLongUrlMap := repository.ProvideShortUrlToLongUrlMap()
	rwMutex := repository.ProvideMutex()
	shortUrlRepositoryImpl := repository.NewShortUrlRepositoryImpl(longUrlToShortUrlMap, shortUrlToLongUrlMap, rwMutex)
	shortUrlServiceImpl := service.NewShortUrlServiceImpl(shortUrlRepositoryImpl)
	shortUrlHandlerImpl := resthandler.NewShortUrlHandlerImpl(shortUrlServiceImpl)
	routerImpl := router.NewRouterImpl(shortUrlHandlerImpl)
	return routerImpl
}
